add typing
ptr-yudai/ptrlib pull request #15
Opened 2022-12-20 16:57 UTC by keymoon-ctf

# add typing
## What's this Pull Request for?
Choose one or more of the following items.

- [x] Bug fix
- [ ] Add/Remove feature
- [x] Cleaning code (including optimization/typo fix)
- [ ] Others

Please explain the detail here:

## What have you done so far?
Tell me what you've tested to assure your change is right.

- [ ] All tests passed on your machine (`python -m unittest`)
- [ ] Added test cases for new feature
- [ ] Nothing / Test not required

(It's not mandatory to check even one of them, but test cases make it easy for the author to review your PR.)

## Comment
\<Your Comment (if any)>

2022-12-20 17:24 UTC, keymoon-ctf commented on ptrlib/arch/arm/assembler.py
> +            return None
戻り値が None であることを明確にするために None を追加しました

2022-12-20 17:27 UTC, keymoon-ctf commented on ptrlib/arch/common/assembler.py
> +    if is_arch_intel(arch):
引数が 1 つになっているのに 2 つのままだったので、修正しました（他 1 箇所）

2022-12-20 17:28 UTC, keymoon-ctf commented on ptrlib/arch/intel/archname.py
> +    return bit_by_arch_intel(arch) != -1
`_arm` は `_intel` の間違いだと思われます

2022-12-20 17:29 UTC, keymoon-ctf commented on ptrlib/arch/arm/assembler.py
> +       entry (str): Entry point
entry は bytes ではなく str として用いられているように見えます

2022-12-21 04:52 UTC, ptr-yudai approved these changes
yosaso-

2022-12-21 04:57 UTC, ptr-yudai commented on ptrlib/arch/common/assembler.py
> +            bits = 64
この辺
```suggestion
        if bits is None:
            bits = bit_by_arch_intel(arch)
            if bits == -1: bits = 64
```
みたいにアーキテクチャ名からビット数をguessする実装にしてもらえると :bow:

2022-12-28 11:43 UTC, ptr-yudai commented
assembleのバグだけ先にマージしました。 https://github.com/ptr-yudai/ptrlib/pull/16

2023-01-07 07:08 UTC, keymoon-ctf commented on ptrlib/pwn/dynlink/dl.py
> +    addr_relplt += proc_base
`section` だと `proc_base` が二重に足されないでしょうか。目にとまったのでそれっぽく直しましたが、大丈夫そうなら戻しておいてください

2023-01-07 07:10 UTC, keymoon-ctf commented on ptrlib/filestruct/elf/enums.py
> -
定義が重複していたので消したシリーズ(1)です

2023-01-07 07:11 UTC, keymoon-ctf commented on ptrlib/filestruct/elf/elf.py
> -            return False
重複していたので消したシリーズ(2)です。後にあったsspの方が強そうだったのでこっちを消しましたが、逆だったら変えておいていただきたいです:bow:

https://github.com/ptr-yudai/ptrlib/blob/61f1966f06f3152885fd38b67d8b8c03a258ea2b/ptrlib/filestruct/elf/elf.py#L422-L435

2023-01-07 07:12 UTC, keymoon-ctf commented on ptrlib/filestruct/elf/elf.py
> -        self._base = base
重複していたので消したシリーズ(3)です。

2023-01-07 07:14 UTC, keymoon-ctf commented on ptrlib/filestruct/elf/elf.py
> +    def set_base(self, base):
`set_base` のデフォルト引数がNoneなのはおかしいと思ったので修正しました。pltも同様の修正を加えました。

https://github.com/ptr-yudai/ptrlib/blob/61f1966f06f3152885fd38b67d8b8c03a258ea2b/ptrlib/filestruct/elf/elf.py#L159

2023-01-07 07:16 UTC, keymoon-ctf commented
struct とパーサ周りは typing と相性が悪そうなので一旦後回しにして、他の部分に型をつけました。挙動に影響しそうな修正にはコメントをつけたのでご参照ください:bow:

2023-01-09 04:56 UTC, ptr-yudai requested changes

2023-01-09 04:56 UTC, ptr-yudai commented on ptrlib/filestruct/elf/elf.py
> +    def set_base(self, base):
`set_base` は以前はNoneを渡すとベースアドレスを消す（総当りなどでやり直して取り消したいときに消す）実装になっていましたが、今は0を渡す仕様なので良いです。
`plt`は何も渡さないと`.plt`セクションのアドレスを取得する仕様になっていました。（↓に引っかかる）
https://github.com/ptr-yudai/ptrlib/blob/61f1966f06f3152885fd38b67d8b8c03a258ea2b/ptrlib/filestruct/elf/elf.py#L176-L178

`section`メソッドができて`plt`メソッドから取得する必要がなくなったので、上記2行を削除しておいてほしいです。

2023-01-09 04:56 UTC, ptr-yudai commented on ptrlib/connection/tube.py
> +    # TODO: proper typing
ここのTODOは何ですか？

2023-01-13 08:25 UTC, keymoon-ctf commented on ptrlib/connection/tube.py
> +    # TODO: proper typing
group でマッチした場合とそうでない場合を型で表現することが難しいので、型が不完全なことを示すと共に設計も含めて見直したいなあという気持ちでの TODO です。

2023-01-16 09:55 UTC, ptr-yudai approved these changes

2023-01-16 09:56 UTC, merged